- name: Set up nginx folder
  become: true
  file:
    path: "{{ nginx_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    state: directory

- name: Set up nginx website folders
  become: true
  become_user: "{{ nginx_user }}"
  file:
    path: "{{ nginx_path }}/conf.d/{{ item }}/www"
    state: directory
  loop: "{{ domains }}"

- name: Generate nginx config for website
  become: true
  become_user: "{{ nginx_user }}"
  template:
    src: www.conf.j2
    dest: "{{ nginx_path }}/conf.d/{{ item }}/www.conf"
  loop: "{{ domains }}"

- name: Set up podman ports
  import_role:
    name: register_ports
  vars:
    tcp_ports:
      - 443
    purge_ports: false
