plex_data_owner: plex_docker
plex_data_path: /var/local/plex
plex_data_links:
  - source: /mnt/music
    target: music
  - source: /mnt/movies
    target: movies

plex_container_name: plex
plex_networks:
  - name: bridge

# network
plex_domains: 
  - domain_name: domain.net
    server_names:
      - plex.domain.net
      - media.domain.net
  - domain_name: domain.com
    server_names:
      - plex.domain.com

plex_direct_port: 32400

# nginx
nginx_config_path: /var/local/nginx
