# plex
username: "{{ podman_username }}"
app_path: /app/plex
media_path: /data/Media

# podman
container: plex-server
networks: 
  - "{{ podman_network }}"
direct_port: 32480

# network
domains: "{{ host_domains }}"
server_prefix: plex

# nginx
nginx_path: "{{ nginx_path }}"
nginx_user: "{{ podman_username }}"
