- name: Set up conf.d folder
  become: yes
  file:
    path: "{{ nginx_conf_d_path }}"
    state: directory

- name: Set up certs folder
  become: yes
  file:
    path: "{{ nginx_certs_path }}"
    state: directory

- name: Set up docker networks
  docker_network: 
    name: "{{ item.name }}"
  loop: "{{ nginx_networks | unique }}"

- name: Start nginx container
  docker_container:
    name: nginx
    image: nginx
    volumes:
      - "/bin/netstat:/bin/netstat:ro"
      - "{{ nginx_conf_d_path }}:/etc/nginx/conf.d":ro
      - "{{ nginx_certs_path }}:/etc/nginx/certs":ro
    ports: "{{ nginx_ports | unique | map('string') | map('regex_replace', '([0-9]+)', '\\1:\\1') }}"
    networks: "{{ nginx_networks | unique }}"
    purge_networks: "{{ purge_nginx_networks }}"
    networks_cli_compatible: no
    container_default_behavior: no_defaults
    restart_policy: always
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp"
        - "|" 
        - "grep:{{ nginx_ports | first | string }}"
      interval: 10s
      timeout: 2s
      retries: 3

- name: Sanity check for all ports listened
  wait_for:
    port: "{{ item }}"
    timeout: 5
  loop: "{{ nginx_ports | unique }}"
