interactive_username: interacitve_user_login
interactive_password: an0th3r_we@k!p4ssw0rd#
# ssh public key as text (not a file path); replace with the actual key
interactive_ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NjustaexsamplePbUa6KGxujatwihavID09cIQcE1UC8x
