mysql_data_path: /var/local/mysql

mysql_container_name: mysql
mysql_networks:
  - name: mysql_db

mysql_root_password: some_secret_password

mysql_databse: mysql_default_db
mysql_username: non_root_user
mysql_password: user_password

