---

- name: Print all local variables
  hosts: localhost
  tasks:
    - debug:
        var: hostvars[inventory_hostname]

- name: print all hostnames
  hosts: all
  become: true
  tasks:
    - debug:
        msg: "hostname is: {{ inventory_hostname }}"
