---

- name: Update existing packages
  hosts: file
  become: true
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

- name: Set up Docker environment
  hosts: file
  become: true
  roles:
    - role: docker

- name: Set up rclone drives
  hosts: file
  roles:
    - role: rclone

- name: Set up file browser
  hosts: file
  vars:
    filebrowser_data_links: "{{ file_data_links }}"
    filebrowser_networks: "{{ file_networks }}"
    filebrowser_domains: "{{ file_domains }}"
  roles:
    - role: filebrowser

- name: Set up SSL certificates
  hosts: file
  roles:
    - role: certbot

- name: Set up nginx
  hosts: file
  vars:
    nginx_networks: "{{ file_networks }}"
    nginx_purge_networks: false
    nginx_run: true
  roles:
    - role: nginx
