---

- name: Update existing apt packages
  hosts: media
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: safe

- name: Set up Docker environment
  hosts: media
  become: yes
  vars:
    docker_edition: 'ce'
    docker_package_state: present
  roles:
    - role: docker

- name: Set up rclone drives
  hosts: media
  roles:
    - role: rclone
