---

- name: Update existing packages
  hosts: media
  become: yes
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

- name: Set up Docker environment
  hosts: media
  become: yes
  roles:
    - role: docker

- name: Set up rclone drives
  hosts: media
  roles:
    - role: rclone

- name: Set up SSL certificates
  hosts: media
  roles:
    - role: certbot

- name: Set up PLEX server
  hosts: media
  vars:
    plex_networks: "{{ media_networks }}"
  roles:
    - role: plex

- name: Set up nginx
  hosts: media
  vars:
    nginx_networks: "{{ media_networks }}"
    nginx_purge_networks: no
    nginx_ports: 
      - 443
    nginx_purge_ports: no
    nginx_contents: {}
    nginx_purge_contents: no
    nginx_run: yes
  roles:
    - role: nginx
