---

- name: Update existing packages
  hosts: wordpress
  become: yes
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

- name: Set up Docker environment
  hosts: wordpress
  become: yes
  roles:
    - role: docker

- name: Set up SSL certificates
  hosts: wordpress
  roles:
    - role: certbot

- name: Set up www data path
  hosts: wordpress
  become: yes
  tasks:
    - file:
        path: "{{ www_data_path }}"
        owner: "{{ ansible_username }}"
        group: "{{ ansible_username }}"
        state: directory

- name: Set up MySQL
  hosts: wordpress
  vars:
    mysql_container_name: "{{ www_db_container }}"
    mysql_data_path: "{{ www_db_data_path }}"
    mysql_data_owner: "{{ www_db_owner }}"
    mysql_networks: "{{ www_networks }}"
    mysql_root_password: "{{ www_db_root_password }}"
    mysql_databse: "{{ www_db_name }}"
    mysql_username: "{{ www_db_username }}"
    mysql_password: "{{ www_db_password }}"
  roles:
    - role: mysql

- name: Set up wordpress
  hosts: wordpress
  vars:
    wordpress_container_name: "{{ www_wp_container }}"
    wordpress_data_path: "{{ www_wp_data_path }}" 
    wordpress_data_owner: "{{ www_wp_owner }}"
    wordpress_networks: "{{ www_networks }}"
    wordpress_db_host: "{{ www_db_container }}"
    wordpress_db_name: "{{ www_db_name }}"
    wordpress_db_username: "{{ www_db_username }}"
    wordpress_db_password: "{{ www_db_password }}"
  roles:
    - role: wordpress

- name: Set up www routing rules
  hosts: wordpress
  roles:
    - role: www

- name: Set up nginx
  hosts: wordpress
  vars:
    nginx_networks: "{{ www_networks }}"
    nginx_purge_networks: no
    nginx_ports: "{{ www_ports }}"
    nginx_purge_ports: no
    nginx_contents: "{{ www_static_file_contents }}"
    nginx_purge_contents: no
    nginx_run: yes
  roles:
    - role: nginx
