---

- name: Update existing packages
  hosts: xray
  become: true
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

- name: Set up Docker environment
  hosts: xray
  roles:
    - role: xray
