---

- name: Update existing packages
  hosts: xray
  become: yes
  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

- name: Set up Docker environment
  hosts: xray
  become: yes
  roles:
    - role: docker

- name: Set up SSL certificates
  hosts: xray
  roles:
    - role: certbot

- name: Set up www site
  hosts: xray
  roles:
    - role: www

- name: Set up xray
  hosts: xray
  roles:
    - role: xray

- name: Set up nginx
  hosts: xray
  vars:
    nginx_networks:
      - name: bridge
    nginx_purge_networks: no
    nginx_contents: "{{ www_static_file_contents }}"
    nginx_purge_contents: no
    nginx_run: yes
  roles:
    - role: nginx
