---
# create user and group
- name: Set up user group
  become: true
  group:
    name: "{{ username }}"
    gid: "{{ uid | int }}"
    state: present

- name: create hashed password
  set_fact:
    hashed_password: "{{ password | password_hash('sha512') }}"
  when: password is defined

- name: Set up user
  become: true
  user:
    name: "{{ username }}"
    password: "{{ hashed_password | default('!') }}"
    update_password: on_create
    uid: "{{ uid | int }}"
    group: "{{ username }}"
    groups: "{{ user_groups }}"
    shell: /bin/bash
    create_home: true
    password_lock: "{{ password is not defined }}"
    comment: "{{ comment }}"
    state: present

- name: Set subuid and subgid range
  become: true
  lineinfile:
    path: "/etc/{{ item }}"
    regexp: "^{{ username }}"
    line: "{{ username }}:{{ uid | int + 1 }}:65535"
  loop:
    - subuid
    - subgid

# Set ansible remote temp folder
- name: Create ansible remote temp folder
  become: true
  file: 
    path: "/home/{{ username }}/.ansible/tmp"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: true
    state: directory

# ssh public key for remote login
- name: Add ssh public key
  become: true
  become_user: "{{ username }}"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_public_key_file) }}"
    exclusive: true
    state: present
  when: ssh_public_key_file is defined

- name: Remove ssh public key
  become: true
  become_user: "{{ username }}"
  file: 
    path: "/home/{{ username }}/.ssh/authorized_keys"
    state: absent
  when: ssh_public_key_file is not defined

# user session linger
- name: Set up user linger
  block:
    - name: Enable user linger
      become: true
      shell: 
        cmd: "loginctl enable-linger {{ username }}"
        creates: "/var/lib/systemd/linger/{{ username }}"
    - name: Export XDG_RUNTIME_DIR when su
      become: true
      become_user: "{{ username }}"
      lineinfile:
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export XDG_RUNTIME_DIR="
        line: 'export XDG_RUNTIME_DIR="/run/user/{{ uid }}"'
    - name: Export DBUS_SESSION_BUS_ADDRESS when su
      become: true
      become_user: "{{ username }}"
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export DBUS_SESSION_BUS_ADDRESS="
        line: 'export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/{{ uid }}/bus"'
  when: linger

- name: Remove user linger
  block:
    - name: Disable user linger
      become: true
      shell: 
        cmd: "loginctl disable-linger {{ username }}"
        removes: "/var/lib/systemd/linger/{{ username }}"
    - name: Do not set XDG_RUNTIME_DIR when su
      become: true
      become_user: "{{ username }}"
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export XDG_RUNTIME_DIR="
        state: absent
    - name: Export DBUS_SESSION_BUS_ADDRESS when su
      become: true
      become_user: "{{ username }}"
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export DBUS_SESSION_BUS_ADDRESS="
        state: absent
  when: not linger

# set up sudo
- name: Grant sudo privilege
  become: true
  copy:
    content: "{{ username }} ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/{{ username }}"
    mode: "600"
  when: sudoer and password is defined

- name: Grant no password sudo privilege
  become: true
  copy:
    content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ username }}"
    mode: "600"
  when: sudoer and password is not defined

- name: Remove sudo privilege
  become: true
  file:
    path: "/etc/sudoers.d/{{ username }}"
    state: absent
  when: not sudoer
  