---
# create user and group
- name: Set up user group
  group:
    name: "{{ username }}"
    gid: "{{ uid | int }}"
    state: present

- name: Set up user
  user:
    name: "{{ username }}"
    password: "{{ (password | length > 0) | ternary(password | password_hash('sha512'), '!') }}"
    update_password: on_create
    uid: "{{ uid | int }}"
    group: "{{ username }}"
    groups: "{{ user_groups }}"
    shell: /bin/bash
    create_home: yes
    password_lock: "{{ password | length == 0 }}"
    comment: "{{ comment }}"
    state: present

- name: Set subuid and subgid range
  lineinfile:
    path: "/etc/{{ item }}"
    regexp: "^{{ username }}"
    line: "{{ username }}:{{ uid | int + 1 }}:65535"
  loop:
    - subuid
    - subgid

# Set ansible remote temp folder
- name: Create ansible remote temp folder
  file: 
    path: "/home/{{ username }}/.ansible/tmp"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    state: directory

# ssh public key for remote login
- name: Add ssh public key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_public_key_file) }}"
    exclusive: yes
    state: present
  when: ssh_public_key_file | length > 0

- name: Remove ssh public key
  file: 
    path: "/home/{{ username }}/.ssh/authorized_keys"
    state: absent
  when: ssh_public_key_file | length == 0

# user session linger
- name: Set up user linger
  block:
    - name: Enable user linger
      shell: 
        cmd: "loginctl enable-linger {{ username }}"
        creates: "/var/lib/systemd/linger/{{ username }}"
    - name: Export XDG_RUNTIME_DIR when su
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export XDG_RUNTIME_DIR="
        line: 'export XDG_RUNTIME_DIR="/run/user/{{ uid }}"'
    - name: Export DBUS_SESSION_BUS_ADDRESS when su
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export DBUS_SESSION_BUS_ADDRESS="
        line: 'export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/{{ uid }}/bus"'
  when: linger

- name: Remove user linger
  block:
    - name: Disable user linger
      shell: 
        cmd: "loginctl disable-linger {{ username }}"
        removes: "/var/lib/systemd/linger/{{ username }}"
    - name: Do not set XDG_RUNTIME_DIR when su
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export XDG_RUNTIME_DIR="
        state: absent
    - name: Export DBUS_SESSION_BUS_ADDRESS when su
      lineinfile: 
        path: "/home/{{ username }}/.bashrc"
        regexp: "^export DBUS_SESSION_BUS_ADDRESS="
        state: absent
  when: not linger

# set up sudo
- name: Grant sudo privilege
  copy:
    content: "{{ username }} ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/{{ username }}"
    mode: "600"
  when: sudoer

- name: Remove sudo privilege
  file:
    path: "/etc/sudoers.d/{{ username }}"
    state: absent
  when: not sudoer
  