- name: Set up wordpress data owner group
  become: yes
  group:
    name: "{{ wordpress_data_owner }}"
    gid: "{{ wordpress_data_uid | int }}"
    state: present

- name: Set up wordpress data owner
  become: yes
  user:
    name: "{{ wordpress_data_owner }}"
    group: "{{ wordpress_data_owner }}"
    comment: "wordpress data owner"
    home: /
    shell: /sbin/nologin
    uid: "{{ wordpress_data_uid | int }}"
    password_lock: yes
    system: yes
    state: present

- name: Set up data folder
  become: yes
  file:
    path: "{{ wordpress_data_path }}"
    owner: "{{ wordpress_data_owner }}"
    group: "{{ wordpress_data_owner }}"
    recurse: yes
    state: directory

- name: Set up docker networks
  docker_network: 
    name: "{{ item.name }}"
  loop: "{{ wordpress_networks }}"

- name: Start wordpress container
  community.general.docker_container:
    name: "{{ wordpress_container_name }}"
    image: wordpress
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
      WORDPRESS_DB_USER: "{{ wordpress_db_username }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
    volumes:
      - "/bin/netstat:/bin/netstat:ro"
      - "{{ wordpress_data_path }}:/var/www/html"
    networks: "{{ wordpress_networks }}"
    purge_networks: yes
    networks_cli_compatible: yes
    container_default_behavior: no_defaults
    restart_policy: always
    pull: yes
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp | grep -q :80"
      interval: 10s
      timeout: 2s
      retries: 3

    