- name: Set up nginx folder
  become: yes
  file:
    path: "{{ nginx_config_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Set up nginx website folders
  file:
    path: "{{ nginx_config_path }}/conf.d/{{ item.domain_name }}/www"
    state: directory
  loop: "{{ www_domains }}"

- name: Generate nginx config for website
  template:
    src: www.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item.domain_name }}/www.conf"
  loop: "{{ www_domains }}"

- name: Generate nginx config for static locations
  template:
    src: www/static.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item.domain_name }}/www/static.conf"
  loop: "{{ www_domains }}"
  when: www_static_site

- name: Generate nginx config for wordpress locations
  template:
    src: www/wordpress.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item.domain_name }}/www/wordpress.conf"
  loop: "{{ www_domains }}"
  when: www_wordpress_site

- name: Generate nginx config for proxy locations
  template:
    src: www/proxy.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item.domain_name }}/www/proxy.conf"
  loop: "{{ www_domains }}"
  when: www_proxy_site
