# Website
www_data_path: /var/local/www
www_domains: 
  - domain_name: domain.net
    server_names:
      - domain.net
      - www.domain.net
  - domain_name: domain.com
    server_names:
      - www.domain.com
      - site.domain.com

# Static File Server
www_static_site: yes
www_static_file_mount: "/srv/www/static"
www_static_locations:
  - path: /index.html
    root: "{{ www_static_file_mount }}"
  - path: /error.html
    root: /usr/share/nginx/html/50x.html

# Wordpress
www_wordpress_site: yes
www_wp_container: www_wordpress

# certbot
certbot_path: /var/local/certbot

# nginx
nginx_config_path: /var/local/nginx
