- name: Install screen tool
  become: true
  ansible.builtin.package:
    name: screen
    state: present

- name: Install tree tool
  become: true
  ansible.builtin.package:
    name: tree
    state: present

- name: Reset SSH connection to apply changes
  ansible.builtin.meta: reset_connection
