- name: set scoped var for current role
  set_fact:
    role_vars_interactive_access:
      username: "{{ username }}"
      password: "{{ password }}"
      ssh_public_key_file: "{{ ssh_public_key_file }}"
      user_groups: "{{ user_groups }}"
      uid: "{{ uid }}"
      sudoer: "{{ sudoer }}"

- name: Set up interactive user
  include_role:
    name: user
  vars:
    username: "{{ role_vars_interactive_access.username }}"
    password: "{{ role_vars_interactive_access.password }}"
    ssh_public_key_file: "{{ role_vars_interactive_access.ssh_public_key_file }}"
    user_groups: "{{ role_vars_interactive_access.user_groups }}"
    uid: "{{ role_vars_interactive_access.uid }}"
    sudoer: "{{ role_vars_interactive_access.sudoer }}"
    comment: "interactive user {{ role_vars_interactive_access.username }}"

- name: Install screen tool
  dnf:
    name: screen
    state: present
    
- name: Reset SSH connection to apply changes
  meta: reset_connection
