- name: Create interactive user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    comment: "interactive user"
    groups: "{{ user_groups }}"
    shell: /bin/bash
    create_home: yes
    update_password: on_create
    state: present

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_public_key_file) }}"
    state: present

- name: Grant sudo privilege
  copy:
    content: "{{ username }} ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/{{ username }}"
    mode: 0600
  when: sudoer

- name: Remove sudo privilege
  file:
    path: "/etc/sudoers.d/{{ username }}"
    state: absent
  when: not sudoer
