### Set up facts
- name: Add specified ports to existing ports list
  set_fact:
    tcp_ports: "{{ ( tcp_ports + ansible_local.podman_ports.tcp | default([]) ) | unique }}"
    udp_ports: "{{ ( udp_ports + ansible_local.podman_ports.udp | default([]) ) | unique }}"
  when: not purge_ports

### Set up firewall
- name: Set up service for firewalld
  become: yes
  template:
    src: podman.xml.j2
    dest: /etc/firewalld/services/podman.xml

- name: Reload firewalld
  become: yes
  systemd:
    name: firewalld
    enabled: yes
    state: reloaded

- name: Enable podman service in firewalld
  become: yes
  ansible.posix.firewalld:
    service: podman
    state: enabled
    immediate: yes
    permanent: yes

### Save facts
- name: Save facts
  copy: 
    content: "{{ {
      'tcp': tcp_ports,
      'udp': udp_ports,
    } | to_nice_json }}" 
    dest: /etc/ansible/facts.d/podman_ports.fact
    