- name: Install podman with supporting packages
  become: true
  ansible.builtin.package:
    name:
      - podman
      - uidmap
      - python3-podman
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
    APT_LISTCHANGES_FRONTEND: none
  vars:
    dpkg_options: "force-confold,force-confdef"
  async: 300
  poll: 10
  register: podman_package_install_result
  # 开启重试循环：只要任务失败（包括 async 超时），就触发重试
  until: podman_package_install_result is succeeded
  retries: 3 # 最多重试 3 次
  delay: 15 # 失败或超时后，等待 15 秒再重试

- name: Set subuid and subgid range for podman user
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/{{ item }}"
    regexp: "^{{ podman_username }}"
    line: "{{ podman_username }}:{{ podman_uid | int + 1 }}:65535"
  loop:
    - subuid
    - subgid

- name: Setup quadlet directory
  become: true
  become_user: "{{ podman_username }}"
  ansible.builtin.file:
    path: "/home/{{ podman_username }}/.config/containers/systemd"
    recurse: true
    state: directory

- name: Setup default podman bridge network
  become: true
  become_user: "{{ podman_username }}"
  containers.podman.podman_network:
    name: "{{ podman_network }}"
    state: quadlet # noqa: args[module]
    ipv6: true
  notify:
    - Create podman network

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable podman auto-update service
  become: true
  become_user: "{{ podman_username }}"
  ansible.builtin.systemd_service:
    name: "podman-auto-update.service"
    scope: user
    daemon_reload: true
    enabled: true

- name: Start podman auto-update timer
  become: true
  become_user: "{{ podman_username }}"
  ansible.builtin.systemd_service:
    name: "podman-auto-update.timer"
    scope: user
    daemon_reload: true
    enabled: true
    state: started

- name: Enable podman socket service
  become: true
  become_user: "{{ podman_username }}"
  ansible.builtin.systemd_service:
    name: podman.socket
    scope: user
    daemon_reload: true
    enabled: true
    state: started
