- name: Disable priviledged port
  become: true
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '0'

- name: Install podman with supporting packages
  become: true
  dnf:
    name: 
      - podman
      - podman-plugins
      - systemd-container
    state: present
    
- name: Install netstat for health check
  become: true
  dnf:
    name: net-tools
    state: present

- name: Install podman-py for ansible access
  pip: 
    name: podman
    state: present

- name: Create podman network
  become: true
  become_user: "{{ podman_username }}"
  containers.podman.podman_network: 
    name: "{{ podman_network }}"
