- name: Disable priviledged port
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '0'

- name: Install podman
  dnf:
    name: podman
    state: present
    
- name: Install netstat for health check
  dnf:
    name: net-tools
    state: present

- name: Install podman-py for ansible access
  pip: 
    name: podman
    state: present
