xray_data_path: /var/local/xray

xray_domains:
  - domain.net
  - domain.com
xray_path: /xray

xray_container_name: xray
xray_networks:
  - name: bridge
xray_port: 10086

xray_clients:
  - id: 00000000-0000-0000-0000-000000000000
    level: 999
    email: sample@domain.net

# nginx
nginx_config_path: /var/local/nginx
