# xray
xray_path: /app/xray
xray_version: latest

xray_clients:
  - id: 00000000-0000-0000-0000-000000000000
    level: 999
    email: sample@domain.net

# podman
xray_container: xray
xray_stats_port: 80

# www
xray_url_path: /xray/proxy
domains:  # noqa: var-naming[no-role-prefix]
  - domain.net
cloudflare_dns_api_token: ""  # noqa: var-naming[no-role-prefix]

# xray inbound ports
xray_ws_port: 81
xray_ws_v1_port: 82
xray_xhttp_v2_port: 83
xray_xhttp_wg_port: 84
