### xray config
- name: Set up xray folder
  become: true
  file:
    path: "{{ xray_path }}"
    owner: "{{ podman_username }}"
    group: "{{ podman_username }}"
    recurse: true
    state: directory

- name: Set up xray configs
  become: true
  become_user: "{{ podman_username }}"
  block:
    - name: Generate server config
      template:
        src: server_config.json.j2
        dest: "{{ xray_path }}/server_config.json"
        setype: container_file_t
    - name: Set up log folder
      file:
        path: "{{ xray_path }}/log"
        seuser: system_u
        setype: container_file_t
        state: directory
    - name: Set up old log folder
      file:
        path: "{{ xray_path }}/log/old"
        state: directory

### Podman container and service
- name: Create xray container
  become: true
  become_user: "{{ podman_username }}"
  containers.podman.podman_container:
    name: "{{ xray_container }}"
    image: docker.io/teddysun/xray
    label:
      io.containers.autoupdate: registry
      PODMAN_SYSTEMD_UNIT: "container-{{ xray_container }}.service"
    network: host
    volumes:
      - "{{ xray_path }}/server_config.json:/etc/xray/config.json:ro"
      - "{{ xray_path }}/log:/var/log/xray"
    state: created
    healthcheck: "netstat -ntlp | grep -q :{{ xray_port }}"
    healthcheck_interval: 10s
    healthcheck_timeout: 2s
    healthcheck_retries: 3
    generate_systemd:
      path: "/home/{{ podman_username }}/.config/systemd/user"
      new: true
      no_header: true
      force: true

- name: Enable and start xray service
  become: true
  become_user: "{{ podman_username }}"
  systemd:
    name: "container-{{ xray_container }}.service"
    scope: user
    daemon_reload: true
    enabled: true
    state: started

- name: Sanity check for xray port listened
  wait_for:
    port: "{{ xray_port }}"
    timeout: 5

- name: Setup logrotate
  become: true
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ xray_container }}_log"

### nginx config
- name: Generate nginx config for xray
  become: true
  become_user: "{{ podman_username }}"
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_path }}/conf.d/{{ item }}/www/xray.conf"
    setype: container_file_t
  loop: "{{ domains }}"
  notify: Reload nginx
