- name: Set up xray folder
  become: yes
  file:
    path: "{{ xray_data_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Generate xray server config
  template:
    src: server_config.json.j2
    dest: "{{ xray_data_path }}/server_config.json"

- name: Set up xray log folder
  file:
    path: "{{ xray_data_path }}/log"
    state: directory

- name: Set up nginx folder
  become: yes
  file:
    path: "{{ nginx_config_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Set up nginx site folders
  file:
    path: "{{ nginx_config_path }}/conf.d/{{ item }}/www"
    state: directory
  loop: "{{ xray_domains }}"

- name: Generate nginx config for xray
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item }}/www/xray.conf"
  loop: "{{ xray_domains }}"

- name: Set up docker networks
  docker_network: 
    name: "{{ item.name }}"
  loop: "{{ xray_networks }}"

- name: Start xray container
  community.general.docker_container:
    name: "{{ xray_container_name }}"
    image: teddysun/xray
    volumes:
      - "{{ xray_data_path }}/server_config.json:/etc/xray/config.json:ro"
      - "{{ xray_data_path }}/log:/var/log/xray"
    networks: "{{ xray_networks }}"
    purge_networks: yes
    networks_cli_compatible: yes
    container_default_behavior: no_defaults
    restart_policy: always
    pull: yes
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp | grep -q :{{ xray_port }}"
      interval: 10s
      timeout: 2s
      retries: 3
