- name: Get ansible user info
  getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Set up xray folder
  become: yes
  file:
    path: "{{ xray_data_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Generate xray server config
  template:
    src: server_config.json.j2
    dest: "{{ xray_data_path }}/server_config.json"

- name: Set up xray log folder
  file:
    path: "{{ xray_data_path }}/log"
    state: directory

- name: Set up nginx folder
  become: yes
  file:
    path: "{{ nginx_config_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Set up nginx site folders
  file:
    path: "{{ nginx_config_path }}/conf.d/{{ item }}/www"
    state: directory
  loop: "{{ xray_domains }}"

- name: Generate nginx config for xray
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}/conf.d/{{ item }}/www/xray.conf"
  loop: "{{ xray_domains }}"

- name: Create firewalld service rule
  become: yes
  copy:
    src: xray.xml
    dest: /usr/lib/firewalld/services
    mode: "644"
  notify: Reload firewalld

- meta: flush_handlers

- name: Enable firewalld service rule
  become: yes
  ansible.posix.firewalld:
    service: xray
    state: enabled
    immediate: yes
    permanent: yes

- name: Start xray container
  community.general.docker_container:
    name: "{{ xray_container_name }}"
    image: teddysun/xray
    volumes:
      - "{{ xray_data_path }}/server_config.json:/etc/xray/config.json:ro"
      - "{{ xray_data_path }}/log:/var/log/xray"
    user: "{{ getent_passwd[ansible_user][1] }}:{{ getent_passwd[ansible_user][2] }}"
    userns_mode: host 
    network_mode: host
    purge_networks: yes
    networks_cli_compatible: yes
    container_default_behavior: no_defaults
    restart_policy: always
    pull: yes
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp | grep -q :{{ xray_port }}"
      interval: 10s
      timeout: 2s
      retries: 3
