- name: Get ansible user info
  getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Set mysql data owner uid
  set_fact:
    mysql_data_uid: "{{ getent_passwd[ansible_user][1] | int + 999 }}"

- name: Set up mysql data owner group
  become: yes
  group:
    name: "{{ mysql_data_owner }}"
    gid: "{{ mysql_data_uid | int }}"
    state: present

- name: Set up mysql data owner
  become: yes
  user:
    name: "{{ mysql_data_owner }}"
    group: "{{ mysql_data_owner }}"
    comment: "mysql data owner"
    home: /
    shell: /sbin/nologin
    uid: "{{ mysql_data_uid | int }}"
    password_lock: yes
    system: yes
    state: present

- name: Set up data folder
  become: yes
  file:
    path: "{{ mysql_data_path }}"
    owner: "{{ mysql_data_owner }}"
    group: "{{ mysql_data_owner }}"
    recurse: yes
    state: directory

- name: Set up docker networks
  docker_network: 
    name: "{{ item.name }}"
  loop: "{{ mysql_networks }}"

- name: Start MySQL container
  community.general.docker_container:
    name: "{{ mysql_container_name }}"
    image: mariadb
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_databse }}"
      MYSQL_USER: "{{ mysql_username }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
      - "/bin/netstat:/bin/netstat:ro"
      - "{{ mysql_data_path }}:/var/lib/mysql"
    networks: "{{ mysql_networks }}"
    network_mode: default
    purge_networks: yes
    networks_cli_compatible: yes
    container_default_behavior: no_defaults
    restart_policy: always
    pull: yes
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp | grep -q :3306" 
      interval: 10s
      timeout: 2s
      retries: 3
