- name: Set up data folder
  become: yes
  file:
    path: "{{ mysql_data_path }}"
    state: directory

- name: Set up docker networks
  docker_network: 
    name: "{{ item.name }}"
  loop: "{{ mysql_networks }}"

- name: Start MySQL container
  docker_container:
    name: "{{ mysql_container_name }}"
    image: mariadb
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_databse }}"
      MYSQL_USER: "{{ mysql_username }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
      - "/bin/netstat:/bin/netstat:ro"
      - "{{ mysql_data_path }}:/var/lib/mysql"
    networks: "{{ mysql_networks }}"
    purge_networks: yes
    networks_cli_compatible: no
    container_default_behavior: no_defaults
    restart_policy: always
    pull: yes
    recreate: yes
    healthcheck:
      test:
        - CMD-SHELL
        - "netstat -ntlp | grep -q :3306" 
      interval: 10s
      timeout: 2s
      retries: 3
