- name: Set up ansible folder
  become: true
  ansible.builtin.file:
    path: /etc/ansible
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Set up facts folder
  become: true
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    owner: "{{ ansible_username }}"
    group: "{{ ansible_username }}"
    recurse: true
    state: directory
    mode: "0755"

- name: Reset SSH connection to apply changes
  ansible.builtin.meta: reset_connection
