- name: Set up ansible folder
  file:
    path: /etc/ansible
    owner: root
    group: root
    state: directory

- name: Set up facts folder
  file:
    path: /etc/ansible/facts.d
    owner: "{{ ansible_username }}"
    group: "{{ ansible_username }}"
    recurse: yes
    state: directory

- name: Reset SSH connection to apply changes
  meta: reset_connection
