# - name: Set up MySQL
#   include_role:
#     name: mysql
#   vars:
#     mysql_networks: "{{ website_networks }}"

# - name: Set up Wordpress
#   include_role:
#     name: wordpress
#     vars:
#       wordpress_networks: "{{ website_networks }}"
#       wordpress_db_host: "{ mysql_container_name }}"
#       wordpress_db_name: "{{ mysql_databse }}"
#       wordpress_db_username: "{{ mysql_username }}"
#       wordpress_db_password: "{{ mysql_username }}"

- name: Create nginx config folders
  become: yes
  file:
    path: "{{ nginx_conf_d_path }}/{{ website_domain_name }}"
    state: directory

- name: Generate nginx config for website
  become: yes
  template:
    src: www.conf.j2
    dest: "{{ nginx_conf_d_path }}/{{ website_domain_name }}.conf"

- name: Generate nginx config for wordpress site
  become: yes
  template:
    src: www/wordpress.conf.j2
    dest: "{{ nginx_conf_d_path }}/{{ website_domain_name }}/wordpress.conf"

- name: Set up nginx
  include_role:
    name: nginx
  vars:
    nginx_networks: "{{ website_networks }}"
    nginx_ports:
      - 80
      - 443
