- name: Set base user to current ansible user, if not defined
  set_fact:
    base_user: "{{ ansible_user }}"
  when: base_user is not defined 

- name: Get base user info
  getent:
    database: passwd
    key: "{{ base_user }}"

- name: Calculate app user uid and gid
  set_fact:
    app_user_uid: "{{ getent_passwd[base_user][1] | int + uid_offset | int }}"
    app_user_gid: "{{ getent_passwd[base_user][2] | int + gid_offset | default(uid_offset) | int }}"

- name: Set up app user group
  become: true
  group:
    name: "{{ username }}"
    gid: "{{ app_user_gid | int }}"
    state: present

- name: Set up app user
  become: true
  user:
    name: "{{ username }}"
    group: "{{ username }}"
    comment: "{{ comment }}"
    home: /
    shell: /sbin/nologin
    uid: "{{ app_user_uid | int }}"
    password_lock: true
    system: true
    state: present
