- name: Remove old versions of Docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - container-selinux
    state: present

- name: Start docker service
  systemd:
    name: docker
    state: started

- name: Install python + pip
  dnf:
    name: python3-pip
    state: present

- name: Install docker-py for ansible to manage Docker
  pip:
    name: docker

- name: Install netstat for health check
  dnf:
    name: net-tools
    state: present

- name: Add ansible user to 'docker' group for access
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: ansible_docker_user

- name: Test run busybox
  become: yes
  become_user: "{{ ansible_docker_user.name }}"
  community.general.docker_container:
    name: test_busybox
    image: busybox
    container_default_behavior: no_defaults
  ignore_errors: yes
