- name: Remove old versions of Docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - container-selinux
    state: present
    
- name: Generate daemon config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install python + pip
  dnf:
    name: python3-pip
    state: present

- name: Install docker-py for ansible to manage Docker
  pip:
    name: docker

- name: Install netstat for health check
  dnf:
    name: net-tools
    state: present

- name: Add ansible user to 'docker' group for access
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection to apply group changes
  meta: reset_connection
  