- name: Install rclone
  apt:
    name: rclone
    state: latest
    update_cache: yes
  become: yes

- name: Set rclone config
  block:
    - name: Initialize config dirs
      set_fact:
        rclone_config_dirs: 
          - "{{ playbook_dir + '/' + rclone_local_config_dir }}"

    - name: Append group config dirs
      set_fact:
        rclone_config_dirs: "{{ rclone_config_dirs + [ rclone_config_dirs[0] + item + '/' ] }}"
      loop: "{{ group_names }}"
      when: rclone_load_group_config

    - name: Set config file
      blockinfile:
        path: "{{ rclone_remote_config_file_path }}"
        block: "{{ lookup('file', item) }}"
        create: yes
        marker: "# {mark} {{ item | basename }}"
      with_fileglob: "{{ rclone_config_dirs | product('*.yaml') | map('join') }}"
  when: rclone_remote_config_file_path is defined
