---
- name: Bootstrap all hosts
  import_playbook: bootstrap.yaml

- name: Set up xray
  import_playbook: xray.yaml
# - import_playbook: file_server.yaml

# - import_playbook: media_server.yaml

# - import_playbook: seedbox.yaml
