---
- name: Upgrade all packages
  hosts: all
  become: true
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      vars:
        dpkg_options: "force-confold,force-confdef"
      async: 600
      poll: 10
      register: apt_upgrade_result
      # 开启重试循环：只要任务失败（包括 async 超时），就触发重试
      until: apt_upgrade_result is succeeded
      retries: 3 # 最多重试 3 次
      delay: 15 # 失败或超时后，等待 15 秒再重试
