---
- name: Update existing packages
  hosts: xray
  become: true
  tasks:
    - name: Update packages
      package:
        name: "*"
        state: latest

- name: Set up xray
  hosts: xray
  roles:
    - role: xray
