---
argument_specs:
  main:
    short_description: set up a new user 
    options:
      interactive_username:
        type: str
        required: true
        description: name of the user

      intercative_password:
        type: str
        required: false
        no_log: true
        description: password of the user, default to none (password locked)

      interactive_ssh_public_key_file:
        type: str
        required: false
        default: ~/.ssh/id_rsa.pub
        description: login ssh public key file, default to ~/.ssh/id_rsa.pub

      interactive_uid:
        type: int
        required: false
        default: 100000
        description: uid/gid of the user

      interactive_user_groups: 
        type: list
        elements: str
        required: false
        default:
          - users
        description: additional groups the user belongs to

      interactive_sudoer:
        type: bool
        required: false
        default: false
        description: whether user has sudo privilege
